name: Workflow to test the connect to remote server action 

# Controls when the workflow will run
on:

#  pull_request:
#    branches: [ "main" ]
#    types: [opened, synchronize , closed]
    
  workflow_dispatch:

jobs:
  main-job:
    runs-on: ubuntu-22.04

    steps:
      #  Check out the print-arguments action
      - uses: mp30028/wf-actions/actions/connect-to-remote-server@main
        with:
          remote_username: ${{ secrets.REMOTE_USERNAME  }}
          remote_password: ${{ secrets.REMOTE_PASSWORD  }}
          remote_server: ${{ secrets.REMOTE_SERVER  }}
